#include "help.h"
#include <errno.h>
#include <stdio.h>

// these symbols are generated by an xxd translation of xcache.1
extern unsigned char xcache_1[];
extern unsigned int xcache_1_len;

int help(void) {

  int rc = 0;

  // run `man`, making it expect to read from stdin
  errno = 0;
  FILE *man = popen("man --local-file /dev/stdin", "w");
  if (man == NULL) {
    rc = errno == 0 ? ENOMEM : errno;
    goto done;
  }

  // send the contents of our manpage to it
  if (fwrite(xcache_1, xcache_1_len, 1, man) < 1) {
    rc = EIO;
    goto done;
  }

done:
  if (man != NULL)
    (void)pclose(man);

  return rc;
}
