task:
  container:
    image: gcc:11.2
  environment:
    DEBIAN_FRONTEND: noninteractive
    CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined -fuse-ld=gold
    PATH: /opt/cmake-3.21.1-linux-x86_64/bin:${PATH}
    UBSAN_OPTIONS: print_stacktrace=1
  install_script: apt-get update -y && apt-get install --no-install-recommends -y cmake python3-pytest strace
  test_script: uname -sr && mkdir build && cd build && cmake .. && cmake --build . && cmake --build . -- check && cmake --build . -- install
