task:
  container:
    image: gcc:10.3
  environment:
    DEBIAN_FRONTEND: noninteractive
    CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined -fuse-ld=gold
    PATH: /opt/cmake-3.21.1-linux-x86_64/bin:${PATH}
    UBSAN_OPTIONS: print_stacktrace=1
  install_script: wget https://github.com/Kitware/CMake/releases/download/v3.21.1/cmake-3.21.1-linux-x86_64.tar.gz && mkdir -p /opt && tar xvf cmake-3.21.1-linux-x86_64.tar.gz --directory /opt
  test_script: uname -sr && mkdir build && cd build && cmake .. && cmake --build . && cmake --build . -- install
