#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 syscall.h" >&2
    exit 1
fi

cat <<EOT
/* Generated by $0 */

#include <sys/syscall.h>
#include "translate-syscall.h"

const char *translate_syscall(int sysno) {
    switch (sysno) {
EOT
grep --color=none '^#define SYS' "$1" | \
    sort | \
    uniq | \
    sed 's/#define \(SYS_[^ ]\+\) .*/#ifdef \1\n        case \1:\n            return "\1";\n#endif/g'
cat <<EOT
    }
    return "UNKNOWN";
}
EOT
