/* Generated by ./tools/generate-translation.sh */

#include <sys/syscall.h>
#include "translate-syscall.h"

const char *translate_syscall(int sysno) {
    switch (sysno) {
#ifdef SYS_accept4
        case SYS_accept4:
            return "SYS_accept4";
#endif
#ifdef SYS_accept
        case SYS_accept:
            return "SYS_accept";
#endif
#ifdef SYS_access
        case SYS_access:
            return "SYS_access";
#endif
#ifdef SYS_acct
        case SYS_acct:
            return "SYS_acct";
#endif
#ifdef SYS_add_key
        case SYS_add_key:
            return "SYS_add_key";
#endif
#ifdef SYS_adjtimex
        case SYS_adjtimex:
            return "SYS_adjtimex";
#endif
#ifdef SYS_afs_syscall
        case SYS_afs_syscall:
            return "SYS_afs_syscall";
#endif
#ifdef SYS_alarm
        case SYS_alarm:
            return "SYS_alarm";
#endif
#ifdef SYS_arch_prctl
        case SYS_arch_prctl:
            return "SYS_arch_prctl";
#endif
#ifdef SYS_bdflush
        case SYS_bdflush:
            return "SYS_bdflush";
#endif
#ifdef SYS_bind
        case SYS_bind:
            return "SYS_bind";
#endif
#ifdef SYS_break
        case SYS_break:
            return "SYS_break";
#endif
#ifdef SYS_brk
        case SYS_brk:
            return "SYS_brk";
#endif
#ifdef SYS_capget
        case SYS_capget:
            return "SYS_capget";
#endif
#ifdef SYS_capset
        case SYS_capset:
            return "SYS_capset";
#endif
#ifdef SYS_chdir
        case SYS_chdir:
            return "SYS_chdir";
#endif
#ifdef SYS_chmod
        case SYS_chmod:
            return "SYS_chmod";
#endif
#ifdef SYS_chown32
        case SYS_chown32:
            return "SYS_chown32";
#endif
#ifdef SYS_chown
        case SYS_chown:
            return "SYS_chown";
#endif
#ifdef SYS_chroot
        case SYS_chroot:
            return "SYS_chroot";
#endif
#ifdef SYS_clock_adjtime
        case SYS_clock_adjtime:
            return "SYS_clock_adjtime";
#endif
#ifdef SYS_clock_getres
        case SYS_clock_getres:
            return "SYS_clock_getres";
#endif
#ifdef SYS_clock_gettime
        case SYS_clock_gettime:
            return "SYS_clock_gettime";
#endif
#ifdef SYS_clock_nanosleep
        case SYS_clock_nanosleep:
            return "SYS_clock_nanosleep";
#endif
#ifdef SYS_clock_settime
        case SYS_clock_settime:
            return "SYS_clock_settime";
#endif
#ifdef SYS_clone
        case SYS_clone:
            return "SYS_clone";
#endif
#ifdef SYS_close
        case SYS_close:
            return "SYS_close";
#endif
#ifdef SYS_connect
        case SYS_connect:
            return "SYS_connect";
#endif
#ifdef SYS_create_module
        case SYS_create_module:
            return "SYS_create_module";
#endif
#ifdef SYS_creat
        case SYS_creat:
            return "SYS_creat";
#endif
#ifdef SYS_delete_module
        case SYS_delete_module:
            return "SYS_delete_module";
#endif
#ifdef SYS_dup2
        case SYS_dup2:
            return "SYS_dup2";
#endif
#ifdef SYS_dup3
        case SYS_dup3:
            return "SYS_dup3";
#endif
#ifdef SYS_dup
        case SYS_dup:
            return "SYS_dup";
#endif
#ifdef SYS_epoll_create1
        case SYS_epoll_create1:
            return "SYS_epoll_create1";
#endif
#ifdef SYS_epoll_create
        case SYS_epoll_create:
            return "SYS_epoll_create";
#endif
#ifdef SYS_epoll_ctl
        case SYS_epoll_ctl:
            return "SYS_epoll_ctl";
#endif
#ifdef SYS_epoll_ctl_old
        case SYS_epoll_ctl_old:
            return "SYS_epoll_ctl_old";
#endif
#ifdef SYS_epoll_pwait
        case SYS_epoll_pwait:
            return "SYS_epoll_pwait";
#endif
#ifdef SYS_epoll_wait
        case SYS_epoll_wait:
            return "SYS_epoll_wait";
#endif
#ifdef SYS_epoll_wait_old
        case SYS_epoll_wait_old:
            return "SYS_epoll_wait_old";
#endif
#ifdef SYS_eventfd2
        case SYS_eventfd2:
            return "SYS_eventfd2";
#endif
#ifdef SYS_eventfd
        case SYS_eventfd:
            return "SYS_eventfd";
#endif
#ifdef SYS_execve
        case SYS_execve:
            return "SYS_execve";
#endif
#ifdef SYS_exit_group
        case SYS_exit_group:
            return "SYS_exit_group";
#endif
#ifdef SYS_exit
        case SYS_exit:
            return "SYS_exit";
#endif
#ifdef SYS_faccessat
        case SYS_faccessat:
            return "SYS_faccessat";
#endif
#ifdef SYS_fadvise64_64
        case SYS_fadvise64_64:
            return "SYS_fadvise64_64";
#endif
#ifdef SYS_fadvise64
        case SYS_fadvise64:
            return "SYS_fadvise64";
#endif
#ifdef SYS_fallocate
        case SYS_fallocate:
            return "SYS_fallocate";
#endif
#ifdef SYS_fanotify_init
        case SYS_fanotify_init:
            return "SYS_fanotify_init";
#endif
#ifdef SYS_fanotify_mark
        case SYS_fanotify_mark:
            return "SYS_fanotify_mark";
#endif
#ifdef SYS_fchdir
        case SYS_fchdir:
            return "SYS_fchdir";
#endif
#ifdef SYS_fchmodat
        case SYS_fchmodat:
            return "SYS_fchmodat";
#endif
#ifdef SYS_fchmod
        case SYS_fchmod:
            return "SYS_fchmod";
#endif
#ifdef SYS_fchown32
        case SYS_fchown32:
            return "SYS_fchown32";
#endif
#ifdef SYS_fchownat
        case SYS_fchownat:
            return "SYS_fchownat";
#endif
#ifdef SYS_fchown
        case SYS_fchown:
            return "SYS_fchown";
#endif
#ifdef SYS_fcntl64
        case SYS_fcntl64:
            return "SYS_fcntl64";
#endif
#ifdef SYS_fcntl
        case SYS_fcntl:
            return "SYS_fcntl";
#endif
#ifdef SYS_fdatasync
        case SYS_fdatasync:
            return "SYS_fdatasync";
#endif
#ifdef SYS_fgetxattr
        case SYS_fgetxattr:
            return "SYS_fgetxattr";
#endif
#ifdef SYS_flistxattr
        case SYS_flistxattr:
            return "SYS_flistxattr";
#endif
#ifdef SYS_flock
        case SYS_flock:
            return "SYS_flock";
#endif
#ifdef SYS_fork
        case SYS_fork:
            return "SYS_fork";
#endif
#ifdef SYS_fremovexattr
        case SYS_fremovexattr:
            return "SYS_fremovexattr";
#endif
#ifdef SYS_fsetxattr
        case SYS_fsetxattr:
            return "SYS_fsetxattr";
#endif
#ifdef SYS_fstat64
        case SYS_fstat64:
            return "SYS_fstat64";
#endif
#ifdef SYS_fstatat64
        case SYS_fstatat64:
            return "SYS_fstatat64";
#endif
#ifdef SYS_fstatfs64
        case SYS_fstatfs64:
            return "SYS_fstatfs64";
#endif
#ifdef SYS_fstatfs
        case SYS_fstatfs:
            return "SYS_fstatfs";
#endif
#ifdef SYS_fstat
        case SYS_fstat:
            return "SYS_fstat";
#endif
#ifdef SYS_fsync
        case SYS_fsync:
            return "SYS_fsync";
#endif
#ifdef SYS_ftime
        case SYS_ftime:
            return "SYS_ftime";
#endif
#ifdef SYS_ftruncate64
        case SYS_ftruncate64:
            return "SYS_ftruncate64";
#endif
#ifdef SYS_ftruncate
        case SYS_ftruncate:
            return "SYS_ftruncate";
#endif
#ifdef SYS_futex
        case SYS_futex:
            return "SYS_futex";
#endif
#ifdef SYS_futimesat
        case SYS_futimesat:
            return "SYS_futimesat";
#endif
#ifdef SYS_getcpu
        case SYS_getcpu:
            return "SYS_getcpu";
#endif
#ifdef SYS_getcwd
        case SYS_getcwd:
            return "SYS_getcwd";
#endif
#ifdef SYS_getdents64
        case SYS_getdents64:
            return "SYS_getdents64";
#endif
#ifdef SYS_getdents
        case SYS_getdents:
            return "SYS_getdents";
#endif
#ifdef SYS_getegid32
        case SYS_getegid32:
            return "SYS_getegid32";
#endif
#ifdef SYS_getegid
        case SYS_getegid:
            return "SYS_getegid";
#endif
#ifdef SYS_geteuid32
        case SYS_geteuid32:
            return "SYS_geteuid32";
#endif
#ifdef SYS_geteuid
        case SYS_geteuid:
            return "SYS_geteuid";
#endif
#ifdef SYS_getgid32
        case SYS_getgid32:
            return "SYS_getgid32";
#endif
#ifdef SYS_getgid
        case SYS_getgid:
            return "SYS_getgid";
#endif
#ifdef SYS_getgroups32
        case SYS_getgroups32:
            return "SYS_getgroups32";
#endif
#ifdef SYS_getgroups
        case SYS_getgroups:
            return "SYS_getgroups";
#endif
#ifdef SYS_getitimer
        case SYS_getitimer:
            return "SYS_getitimer";
#endif
#ifdef SYS_get_kernel_syms
        case SYS_get_kernel_syms:
            return "SYS_get_kernel_syms";
#endif
#ifdef SYS_get_mempolicy
        case SYS_get_mempolicy:
            return "SYS_get_mempolicy";
#endif
#ifdef SYS_getpeername
        case SYS_getpeername:
            return "SYS_getpeername";
#endif
#ifdef SYS_getpgid
        case SYS_getpgid:
            return "SYS_getpgid";
#endif
#ifdef SYS_getpgrp
        case SYS_getpgrp:
            return "SYS_getpgrp";
#endif
#ifdef SYS_getpid
        case SYS_getpid:
            return "SYS_getpid";
#endif
#ifdef SYS_getpmsg
        case SYS_getpmsg:
            return "SYS_getpmsg";
#endif
#ifdef SYS_getppid
        case SYS_getppid:
            return "SYS_getppid";
#endif
#ifdef SYS_getpriority
        case SYS_getpriority:
            return "SYS_getpriority";
#endif
#ifdef SYS_getresgid32
        case SYS_getresgid32:
            return "SYS_getresgid32";
#endif
#ifdef SYS_getresgid
        case SYS_getresgid:
            return "SYS_getresgid";
#endif
#ifdef SYS_getresuid32
        case SYS_getresuid32:
            return "SYS_getresuid32";
#endif
#ifdef SYS_getresuid
        case SYS_getresuid:
            return "SYS_getresuid";
#endif
#ifdef SYS_getrlimit
        case SYS_getrlimit:
            return "SYS_getrlimit";
#endif
#ifdef SYS_get_robust_list
        case SYS_get_robust_list:
            return "SYS_get_robust_list";
#endif
#ifdef SYS_getrusage
        case SYS_getrusage:
            return "SYS_getrusage";
#endif
#ifdef SYS_getsid
        case SYS_getsid:
            return "SYS_getsid";
#endif
#ifdef SYS_getsockname
        case SYS_getsockname:
            return "SYS_getsockname";
#endif
#ifdef SYS_getsockopt
        case SYS_getsockopt:
            return "SYS_getsockopt";
#endif
#ifdef SYS_get_thread_area
        case SYS_get_thread_area:
            return "SYS_get_thread_area";
#endif
#ifdef SYS_gettid
        case SYS_gettid:
            return "SYS_gettid";
#endif
#ifdef SYS_gettimeofday
        case SYS_gettimeofday:
            return "SYS_gettimeofday";
#endif
#ifdef SYS_getuid32
        case SYS_getuid32:
            return "SYS_getuid32";
#endif
#ifdef SYS_getuid
        case SYS_getuid:
            return "SYS_getuid";
#endif
#ifdef SYS_getxattr
        case SYS_getxattr:
            return "SYS_getxattr";
#endif
#ifdef SYS_gtty
        case SYS_gtty:
            return "SYS_gtty";
#endif
#ifdef SYS_idle
        case SYS_idle:
            return "SYS_idle";
#endif
#ifdef SYS_init_module
        case SYS_init_module:
            return "SYS_init_module";
#endif
#ifdef SYS_inotify_add_watch
        case SYS_inotify_add_watch:
            return "SYS_inotify_add_watch";
#endif
#ifdef SYS_inotify_init1
        case SYS_inotify_init1:
            return "SYS_inotify_init1";
#endif
#ifdef SYS_inotify_init
        case SYS_inotify_init:
            return "SYS_inotify_init";
#endif
#ifdef SYS_inotify_rm_watch
        case SYS_inotify_rm_watch:
            return "SYS_inotify_rm_watch";
#endif
#ifdef SYS_io_cancel
        case SYS_io_cancel:
            return "SYS_io_cancel";
#endif
#ifdef SYS_ioctl
        case SYS_ioctl:
            return "SYS_ioctl";
#endif
#ifdef SYS_io_destroy
        case SYS_io_destroy:
            return "SYS_io_destroy";
#endif
#ifdef SYS_io_getevents
        case SYS_io_getevents:
            return "SYS_io_getevents";
#endif
#ifdef SYS_ioperm
        case SYS_ioperm:
            return "SYS_ioperm";
#endif
#ifdef SYS_iopl
        case SYS_iopl:
            return "SYS_iopl";
#endif
#ifdef SYS_ioprio_get
        case SYS_ioprio_get:
            return "SYS_ioprio_get";
#endif
#ifdef SYS_ioprio_set
        case SYS_ioprio_set:
            return "SYS_ioprio_set";
#endif
#ifdef SYS_io_setup
        case SYS_io_setup:
            return "SYS_io_setup";
#endif
#ifdef SYS_io_submit
        case SYS_io_submit:
            return "SYS_io_submit";
#endif
#ifdef SYS_ipc
        case SYS_ipc:
            return "SYS_ipc";
#endif
#ifdef SYS_kexec_load
        case SYS_kexec_load:
            return "SYS_kexec_load";
#endif
#ifdef SYS_keyctl
        case SYS_keyctl:
            return "SYS_keyctl";
#endif
#ifdef SYS_kill
        case SYS_kill:
            return "SYS_kill";
#endif
#ifdef SYS_lchown32
        case SYS_lchown32:
            return "SYS_lchown32";
#endif
#ifdef SYS_lchown
        case SYS_lchown:
            return "SYS_lchown";
#endif
#ifdef SYS_lgetxattr
        case SYS_lgetxattr:
            return "SYS_lgetxattr";
#endif
#ifdef SYS_linkat
        case SYS_linkat:
            return "SYS_linkat";
#endif
#ifdef SYS_link
        case SYS_link:
            return "SYS_link";
#endif
#ifdef SYS_listen
        case SYS_listen:
            return "SYS_listen";
#endif
#ifdef SYS_listxattr
        case SYS_listxattr:
            return "SYS_listxattr";
#endif
#ifdef SYS_llistxattr
        case SYS_llistxattr:
            return "SYS_llistxattr";
#endif
#ifdef SYS__llseek
        case SYS__llseek:
            return "SYS__llseek";
#endif
#ifdef SYS_lock
        case SYS_lock:
            return "SYS_lock";
#endif
#ifdef SYS_lookup_dcookie
        case SYS_lookup_dcookie:
            return "SYS_lookup_dcookie";
#endif
#ifdef SYS_lremovexattr
        case SYS_lremovexattr:
            return "SYS_lremovexattr";
#endif
#ifdef SYS_lseek
        case SYS_lseek:
            return "SYS_lseek";
#endif
#ifdef SYS_lsetxattr
        case SYS_lsetxattr:
            return "SYS_lsetxattr";
#endif
#ifdef SYS_lstat64
        case SYS_lstat64:
            return "SYS_lstat64";
#endif
#ifdef SYS_lstat
        case SYS_lstat:
            return "SYS_lstat";
#endif
#ifdef SYS_madvise1
        case SYS_madvise1:
            return "SYS_madvise1";
#endif
#ifdef SYS_madvise
        case SYS_madvise:
            return "SYS_madvise";
#endif
#ifdef SYS_mbind
        case SYS_mbind:
            return "SYS_mbind";
#endif
#ifdef SYS_migrate_pages
        case SYS_migrate_pages:
            return "SYS_migrate_pages";
#endif
#ifdef SYS_mincore
        case SYS_mincore:
            return "SYS_mincore";
#endif
#ifdef SYS_mkdirat
        case SYS_mkdirat:
            return "SYS_mkdirat";
#endif
#ifdef SYS_mkdir
        case SYS_mkdir:
            return "SYS_mkdir";
#endif
#ifdef SYS_mknodat
        case SYS_mknodat:
            return "SYS_mknodat";
#endif
#ifdef SYS_mknod
        case SYS_mknod:
            return "SYS_mknod";
#endif
#ifdef SYS_mlockall
        case SYS_mlockall:
            return "SYS_mlockall";
#endif
#ifdef SYS_mlock
        case SYS_mlock:
            return "SYS_mlock";
#endif
#ifdef SYS_mmap2
        case SYS_mmap2:
            return "SYS_mmap2";
#endif
#ifdef SYS_mmap
        case SYS_mmap:
            return "SYS_mmap";
#endif
#ifdef SYS_modify_ldt
        case SYS_modify_ldt:
            return "SYS_modify_ldt";
#endif
#ifdef SYS_mount
        case SYS_mount:
            return "SYS_mount";
#endif
#ifdef SYS_move_pages
        case SYS_move_pages:
            return "SYS_move_pages";
#endif
#ifdef SYS_mprotect
        case SYS_mprotect:
            return "SYS_mprotect";
#endif
#ifdef SYS_mpx
        case SYS_mpx:
            return "SYS_mpx";
#endif
#ifdef SYS_mq_getsetattr
        case SYS_mq_getsetattr:
            return "SYS_mq_getsetattr";
#endif
#ifdef SYS_mq_notify
        case SYS_mq_notify:
            return "SYS_mq_notify";
#endif
#ifdef SYS_mq_open
        case SYS_mq_open:
            return "SYS_mq_open";
#endif
#ifdef SYS_mq_timedreceive
        case SYS_mq_timedreceive:
            return "SYS_mq_timedreceive";
#endif
#ifdef SYS_mq_timedsend
        case SYS_mq_timedsend:
            return "SYS_mq_timedsend";
#endif
#ifdef SYS_mq_unlink
        case SYS_mq_unlink:
            return "SYS_mq_unlink";
#endif
#ifdef SYS_mremap
        case SYS_mremap:
            return "SYS_mremap";
#endif
#ifdef SYS_msgctl
        case SYS_msgctl:
            return "SYS_msgctl";
#endif
#ifdef SYS_msgget
        case SYS_msgget:
            return "SYS_msgget";
#endif
#ifdef SYS_msgrcv
        case SYS_msgrcv:
            return "SYS_msgrcv";
#endif
#ifdef SYS_msgsnd
        case SYS_msgsnd:
            return "SYS_msgsnd";
#endif
#ifdef SYS_msync
        case SYS_msync:
            return "SYS_msync";
#endif
#ifdef SYS_munlockall
        case SYS_munlockall:
            return "SYS_munlockall";
#endif
#ifdef SYS_munlock
        case SYS_munlock:
            return "SYS_munlock";
#endif
#ifdef SYS_munmap
        case SYS_munmap:
            return "SYS_munmap";
#endif
#ifdef SYS_name_to_handle_at
        case SYS_name_to_handle_at:
            return "SYS_name_to_handle_at";
#endif
#ifdef SYS_nanosleep
        case SYS_nanosleep:
            return "SYS_nanosleep";
#endif
#ifdef SYS_newfstatat
        case SYS_newfstatat:
            return "SYS_newfstatat";
#endif
#ifdef SYS__newselect
        case SYS__newselect:
            return "SYS__newselect";
#endif
#ifdef SYS_nfsservctl
        case SYS_nfsservctl:
            return "SYS_nfsservctl";
#endif
#ifdef SYS_nice
        case SYS_nice:
            return "SYS_nice";
#endif
#ifdef SYS_oldfstat
        case SYS_oldfstat:
            return "SYS_oldfstat";
#endif
#ifdef SYS_oldlstat
        case SYS_oldlstat:
            return "SYS_oldlstat";
#endif
#ifdef SYS_oldolduname
        case SYS_oldolduname:
            return "SYS_oldolduname";
#endif
#ifdef SYS_oldstat
        case SYS_oldstat:
            return "SYS_oldstat";
#endif
#ifdef SYS_olduname
        case SYS_olduname:
            return "SYS_olduname";
#endif
#ifdef SYS_openat
        case SYS_openat:
            return "SYS_openat";
#endif
#ifdef SYS_open_by_handle_at
        case SYS_open_by_handle_at:
            return "SYS_open_by_handle_at";
#endif
#ifdef SYS_open
        case SYS_open:
            return "SYS_open";
#endif
#ifdef SYS_pause
        case SYS_pause:
            return "SYS_pause";
#endif
#ifdef SYS_perf_event_open
        case SYS_perf_event_open:
            return "SYS_perf_event_open";
#endif
#ifdef SYS_personality
        case SYS_personality:
            return "SYS_personality";
#endif
#ifdef SYS_pipe2
        case SYS_pipe2:
            return "SYS_pipe2";
#endif
#ifdef SYS_pipe
        case SYS_pipe:
            return "SYS_pipe";
#endif
#ifdef SYS_pivot_root
        case SYS_pivot_root:
            return "SYS_pivot_root";
#endif
#ifdef SYS_poll
        case SYS_poll:
            return "SYS_poll";
#endif
#ifdef SYS_ppoll
        case SYS_ppoll:
            return "SYS_ppoll";
#endif
#ifdef SYS_prctl
        case SYS_prctl:
            return "SYS_prctl";
#endif
#ifdef SYS_pread64
        case SYS_pread64:
            return "SYS_pread64";
#endif
#ifdef SYS_preadv
        case SYS_preadv:
            return "SYS_preadv";
#endif
#ifdef SYS_prlimit64
        case SYS_prlimit64:
            return "SYS_prlimit64";
#endif
#ifdef SYS_process_vm_readv
        case SYS_process_vm_readv:
            return "SYS_process_vm_readv";
#endif
#ifdef SYS_process_vm_writev
        case SYS_process_vm_writev:
            return "SYS_process_vm_writev";
#endif
#ifdef SYS_profil
        case SYS_profil:
            return "SYS_profil";
#endif
#ifdef SYS_prof
        case SYS_prof:
            return "SYS_prof";
#endif
#ifdef SYS_pselect6
        case SYS_pselect6:
            return "SYS_pselect6";
#endif
#ifdef SYS_ptrace
        case SYS_ptrace:
            return "SYS_ptrace";
#endif
#ifdef SYS_putpmsg
        case SYS_putpmsg:
            return "SYS_putpmsg";
#endif
#ifdef SYS_pwrite64
        case SYS_pwrite64:
            return "SYS_pwrite64";
#endif
#ifdef SYS_pwritev
        case SYS_pwritev:
            return "SYS_pwritev";
#endif
#ifdef SYS_query_module
        case SYS_query_module:
            return "SYS_query_module";
#endif
#ifdef SYS_quotactl
        case SYS_quotactl:
            return "SYS_quotactl";
#endif
#ifdef SYS_readahead
        case SYS_readahead:
            return "SYS_readahead";
#endif
#ifdef SYS_readdir
        case SYS_readdir:
            return "SYS_readdir";
#endif
#ifdef SYS_readlinkat
        case SYS_readlinkat:
            return "SYS_readlinkat";
#endif
#ifdef SYS_readlink
        case SYS_readlink:
            return "SYS_readlink";
#endif
#ifdef SYS_read
        case SYS_read:
            return "SYS_read";
#endif
#ifdef SYS_readv
        case SYS_readv:
            return "SYS_readv";
#endif
#ifdef SYS_reboot
        case SYS_reboot:
            return "SYS_reboot";
#endif
#ifdef SYS_recvfrom
        case SYS_recvfrom:
            return "SYS_recvfrom";
#endif
#ifdef SYS_recvmmsg
        case SYS_recvmmsg:
            return "SYS_recvmmsg";
#endif
#ifdef SYS_recvmsg
        case SYS_recvmsg:
            return "SYS_recvmsg";
#endif
#ifdef SYS_remap_file_pages
        case SYS_remap_file_pages:
            return "SYS_remap_file_pages";
#endif
#ifdef SYS_removexattr
        case SYS_removexattr:
            return "SYS_removexattr";
#endif
#ifdef SYS_renameat
        case SYS_renameat:
            return "SYS_renameat";
#endif
#ifdef SYS_rename
        case SYS_rename:
            return "SYS_rename";
#endif
#ifdef SYS_request_key
        case SYS_request_key:
            return "SYS_request_key";
#endif
#ifdef SYS_restart_syscall
        case SYS_restart_syscall:
            return "SYS_restart_syscall";
#endif
#ifdef SYS_rmdir
        case SYS_rmdir:
            return "SYS_rmdir";
#endif
#ifdef SYS_rt_sigaction
        case SYS_rt_sigaction:
            return "SYS_rt_sigaction";
#endif
#ifdef SYS_rt_sigpending
        case SYS_rt_sigpending:
            return "SYS_rt_sigpending";
#endif
#ifdef SYS_rt_sigprocmask
        case SYS_rt_sigprocmask:
            return "SYS_rt_sigprocmask";
#endif
#ifdef SYS_rt_sigqueueinfo
        case SYS_rt_sigqueueinfo:
            return "SYS_rt_sigqueueinfo";
#endif
#ifdef SYS_rt_sigreturn
        case SYS_rt_sigreturn:
            return "SYS_rt_sigreturn";
#endif
#ifdef SYS_rt_sigsuspend
        case SYS_rt_sigsuspend:
            return "SYS_rt_sigsuspend";
#endif
#ifdef SYS_rt_sigtimedwait
        case SYS_rt_sigtimedwait:
            return "SYS_rt_sigtimedwait";
#endif
#ifdef SYS_rt_tgsigqueueinfo
        case SYS_rt_tgsigqueueinfo:
            return "SYS_rt_tgsigqueueinfo";
#endif
#ifdef SYS_sched_getaffinity
        case SYS_sched_getaffinity:
            return "SYS_sched_getaffinity";
#endif
#ifdef SYS_sched_getparam
        case SYS_sched_getparam:
            return "SYS_sched_getparam";
#endif
#ifdef SYS_sched_get_priority_max
        case SYS_sched_get_priority_max:
            return "SYS_sched_get_priority_max";
#endif
#ifdef SYS_sched_get_priority_min
        case SYS_sched_get_priority_min:
            return "SYS_sched_get_priority_min";
#endif
#ifdef SYS_sched_getscheduler
        case SYS_sched_getscheduler:
            return "SYS_sched_getscheduler";
#endif
#ifdef SYS_sched_rr_get_interval
        case SYS_sched_rr_get_interval:
            return "SYS_sched_rr_get_interval";
#endif
#ifdef SYS_sched_setaffinity
        case SYS_sched_setaffinity:
            return "SYS_sched_setaffinity";
#endif
#ifdef SYS_sched_setparam
        case SYS_sched_setparam:
            return "SYS_sched_setparam";
#endif
#ifdef SYS_sched_setscheduler
        case SYS_sched_setscheduler:
            return "SYS_sched_setscheduler";
#endif
#ifdef SYS_sched_yield
        case SYS_sched_yield:
            return "SYS_sched_yield";
#endif
#ifdef SYS_security
        case SYS_security:
            return "SYS_security";
#endif
#ifdef SYS_select
        case SYS_select:
            return "SYS_select";
#endif
#ifdef SYS_semctl
        case SYS_semctl:
            return "SYS_semctl";
#endif
#ifdef SYS_semget
        case SYS_semget:
            return "SYS_semget";
#endif
#ifdef SYS_semop
        case SYS_semop:
            return "SYS_semop";
#endif
#ifdef SYS_semtimedop
        case SYS_semtimedop:
            return "SYS_semtimedop";
#endif
#ifdef SYS_sendfile64
        case SYS_sendfile64:
            return "SYS_sendfile64";
#endif
#ifdef SYS_sendfile
        case SYS_sendfile:
            return "SYS_sendfile";
#endif
#ifdef SYS_sendmmsg
        case SYS_sendmmsg:
            return "SYS_sendmmsg";
#endif
#ifdef SYS_sendmsg
        case SYS_sendmsg:
            return "SYS_sendmsg";
#endif
#ifdef SYS_sendto
        case SYS_sendto:
            return "SYS_sendto";
#endif
#ifdef SYS_setdomainname
        case SYS_setdomainname:
            return "SYS_setdomainname";
#endif
#ifdef SYS_setfsgid32
        case SYS_setfsgid32:
            return "SYS_setfsgid32";
#endif
#ifdef SYS_setfsgid
        case SYS_setfsgid:
            return "SYS_setfsgid";
#endif
#ifdef SYS_setfsuid32
        case SYS_setfsuid32:
            return "SYS_setfsuid32";
#endif
#ifdef SYS_setfsuid
        case SYS_setfsuid:
            return "SYS_setfsuid";
#endif
#ifdef SYS_setgid32
        case SYS_setgid32:
            return "SYS_setgid32";
#endif
#ifdef SYS_setgid
        case SYS_setgid:
            return "SYS_setgid";
#endif
#ifdef SYS_setgroups32
        case SYS_setgroups32:
            return "SYS_setgroups32";
#endif
#ifdef SYS_setgroups
        case SYS_setgroups:
            return "SYS_setgroups";
#endif
#ifdef SYS_sethostname
        case SYS_sethostname:
            return "SYS_sethostname";
#endif
#ifdef SYS_setitimer
        case SYS_setitimer:
            return "SYS_setitimer";
#endif
#ifdef SYS_set_mempolicy
        case SYS_set_mempolicy:
            return "SYS_set_mempolicy";
#endif
#ifdef SYS_setns
        case SYS_setns:
            return "SYS_setns";
#endif
#ifdef SYS_setpgid
        case SYS_setpgid:
            return "SYS_setpgid";
#endif
#ifdef SYS_setpriority
        case SYS_setpriority:
            return "SYS_setpriority";
#endif
#ifdef SYS_setregid32
        case SYS_setregid32:
            return "SYS_setregid32";
#endif
#ifdef SYS_setregid
        case SYS_setregid:
            return "SYS_setregid";
#endif
#ifdef SYS_setresgid32
        case SYS_setresgid32:
            return "SYS_setresgid32";
#endif
#ifdef SYS_setresgid
        case SYS_setresgid:
            return "SYS_setresgid";
#endif
#ifdef SYS_setresuid32
        case SYS_setresuid32:
            return "SYS_setresuid32";
#endif
#ifdef SYS_setresuid
        case SYS_setresuid:
            return "SYS_setresuid";
#endif
#ifdef SYS_setreuid32
        case SYS_setreuid32:
            return "SYS_setreuid32";
#endif
#ifdef SYS_setreuid
        case SYS_setreuid:
            return "SYS_setreuid";
#endif
#ifdef SYS_setrlimit
        case SYS_setrlimit:
            return "SYS_setrlimit";
#endif
#ifdef SYS_set_robust_list
        case SYS_set_robust_list:
            return "SYS_set_robust_list";
#endif
#ifdef SYS_setsid
        case SYS_setsid:
            return "SYS_setsid";
#endif
#ifdef SYS_setsockopt
        case SYS_setsockopt:
            return "SYS_setsockopt";
#endif
#ifdef SYS_set_thread_area
        case SYS_set_thread_area:
            return "SYS_set_thread_area";
#endif
#ifdef SYS_set_tid_address
        case SYS_set_tid_address:
            return "SYS_set_tid_address";
#endif
#ifdef SYS_settimeofday
        case SYS_settimeofday:
            return "SYS_settimeofday";
#endif
#ifdef SYS_setuid32
        case SYS_setuid32:
            return "SYS_setuid32";
#endif
#ifdef SYS_setuid
        case SYS_setuid:
            return "SYS_setuid";
#endif
#ifdef SYS_setxattr
        case SYS_setxattr:
            return "SYS_setxattr";
#endif
#ifdef SYS_sgetmask
        case SYS_sgetmask:
            return "SYS_sgetmask";
#endif
#ifdef SYS_shmat
        case SYS_shmat:
            return "SYS_shmat";
#endif
#ifdef SYS_shmctl
        case SYS_shmctl:
            return "SYS_shmctl";
#endif
#ifdef SYS_shmdt
        case SYS_shmdt:
            return "SYS_shmdt";
#endif
#ifdef SYS_shmget
        case SYS_shmget:
            return "SYS_shmget";
#endif
#ifdef SYS_shutdown
        case SYS_shutdown:
            return "SYS_shutdown";
#endif
#ifdef SYS_sigaction
        case SYS_sigaction:
            return "SYS_sigaction";
#endif
#ifdef SYS_sigaltstack
        case SYS_sigaltstack:
            return "SYS_sigaltstack";
#endif
#ifdef SYS_signalfd4
        case SYS_signalfd4:
            return "SYS_signalfd4";
#endif
#ifdef SYS_signalfd
        case SYS_signalfd:
            return "SYS_signalfd";
#endif
#ifdef SYS_signal
        case SYS_signal:
            return "SYS_signal";
#endif
#ifdef SYS_sigpending
        case SYS_sigpending:
            return "SYS_sigpending";
#endif
#ifdef SYS_sigprocmask
        case SYS_sigprocmask:
            return "SYS_sigprocmask";
#endif
#ifdef SYS_sigreturn
        case SYS_sigreturn:
            return "SYS_sigreturn";
#endif
#ifdef SYS_sigsuspend
        case SYS_sigsuspend:
            return "SYS_sigsuspend";
#endif
#ifdef SYS_socketcall
        case SYS_socketcall:
            return "SYS_socketcall";
#endif
#ifdef SYS_socket
        case SYS_socket:
            return "SYS_socket";
#endif
#ifdef SYS_socketpair
        case SYS_socketpair:
            return "SYS_socketpair";
#endif
#ifdef SYS_splice
        case SYS_splice:
            return "SYS_splice";
#endif
#ifdef SYS_ssetmask
        case SYS_ssetmask:
            return "SYS_ssetmask";
#endif
#ifdef SYS_stat64
        case SYS_stat64:
            return "SYS_stat64";
#endif
#ifdef SYS_statfs64
        case SYS_statfs64:
            return "SYS_statfs64";
#endif
#ifdef SYS_statfs
        case SYS_statfs:
            return "SYS_statfs";
#endif
#ifdef SYS_stat
        case SYS_stat:
            return "SYS_stat";
#endif
#ifdef SYS_stime
        case SYS_stime:
            return "SYS_stime";
#endif
#ifdef SYS_stty
        case SYS_stty:
            return "SYS_stty";
#endif
#ifdef SYS_swapoff
        case SYS_swapoff:
            return "SYS_swapoff";
#endif
#ifdef SYS_swapon
        case SYS_swapon:
            return "SYS_swapon";
#endif
#ifdef SYS_symlinkat
        case SYS_symlinkat:
            return "SYS_symlinkat";
#endif
#ifdef SYS_symlink
        case SYS_symlink:
            return "SYS_symlink";
#endif
#ifdef SYS_sync_file_range
        case SYS_sync_file_range:
            return "SYS_sync_file_range";
#endif
#ifdef SYS_syncfs
        case SYS_syncfs:
            return "SYS_syncfs";
#endif
#ifdef SYS_sync
        case SYS_sync:
            return "SYS_sync";
#endif
#ifdef SYS__sysctl
        case SYS__sysctl:
            return "SYS__sysctl";
#endif
#ifdef SYS_sysfs
        case SYS_sysfs:
            return "SYS_sysfs";
#endif
#ifdef SYS_sysinfo
        case SYS_sysinfo:
            return "SYS_sysinfo";
#endif
#ifdef SYS_syslog
        case SYS_syslog:
            return "SYS_syslog";
#endif
#ifdef SYS_tee
        case SYS_tee:
            return "SYS_tee";
#endif
#ifdef SYS_tgkill
        case SYS_tgkill:
            return "SYS_tgkill";
#endif
#ifdef SYS_time
        case SYS_time:
            return "SYS_time";
#endif
#ifdef SYS_timer_create
        case SYS_timer_create:
            return "SYS_timer_create";
#endif
#ifdef SYS_timer_delete
        case SYS_timer_delete:
            return "SYS_timer_delete";
#endif
#ifdef SYS_timerfd_create
        case SYS_timerfd_create:
            return "SYS_timerfd_create";
#endif
#ifdef SYS_timerfd_gettime
        case SYS_timerfd_gettime:
            return "SYS_timerfd_gettime";
#endif
#ifdef SYS_timerfd_settime
        case SYS_timerfd_settime:
            return "SYS_timerfd_settime";
#endif
#ifdef SYS_timer_getoverrun
        case SYS_timer_getoverrun:
            return "SYS_timer_getoverrun";
#endif
#ifdef SYS_timer_gettime
        case SYS_timer_gettime:
            return "SYS_timer_gettime";
#endif
#ifdef SYS_timer_settime
        case SYS_timer_settime:
            return "SYS_timer_settime";
#endif
#ifdef SYS_times
        case SYS_times:
            return "SYS_times";
#endif
#ifdef SYS_tkill
        case SYS_tkill:
            return "SYS_tkill";
#endif
#ifdef SYS_truncate64
        case SYS_truncate64:
            return "SYS_truncate64";
#endif
#ifdef SYS_truncate
        case SYS_truncate:
            return "SYS_truncate";
#endif
#ifdef SYS_tuxcall
        case SYS_tuxcall:
            return "SYS_tuxcall";
#endif
#ifdef SYS_ugetrlimit
        case SYS_ugetrlimit:
            return "SYS_ugetrlimit";
#endif
#ifdef SYS_ulimit
        case SYS_ulimit:
            return "SYS_ulimit";
#endif
#ifdef SYS_umask
        case SYS_umask:
            return "SYS_umask";
#endif
#ifdef SYS_umount2
        case SYS_umount2:
            return "SYS_umount2";
#endif
#ifdef SYS_umount
        case SYS_umount:
            return "SYS_umount";
#endif
#ifdef SYS_uname
        case SYS_uname:
            return "SYS_uname";
#endif
#ifdef SYS_unlinkat
        case SYS_unlinkat:
            return "SYS_unlinkat";
#endif
#ifdef SYS_unlink
        case SYS_unlink:
            return "SYS_unlink";
#endif
#ifdef SYS_unshare
        case SYS_unshare:
            return "SYS_unshare";
#endif
#ifdef SYS_uselib
        case SYS_uselib:
            return "SYS_uselib";
#endif
#ifdef SYS_ustat
        case SYS_ustat:
            return "SYS_ustat";
#endif
#ifdef SYS_utime
        case SYS_utime:
            return "SYS_utime";
#endif
#ifdef SYS_utimensat
        case SYS_utimensat:
            return "SYS_utimensat";
#endif
#ifdef SYS_utimes
        case SYS_utimes:
            return "SYS_utimes";
#endif
#ifdef SYS_vfork
        case SYS_vfork:
            return "SYS_vfork";
#endif
#ifdef SYS_vhangup
        case SYS_vhangup:
            return "SYS_vhangup";
#endif
#ifdef SYS_vm86
        case SYS_vm86:
            return "SYS_vm86";
#endif
#ifdef SYS_vm86old
        case SYS_vm86old:
            return "SYS_vm86old";
#endif
#ifdef SYS_vmsplice
        case SYS_vmsplice:
            return "SYS_vmsplice";
#endif
#ifdef SYS_vserver
        case SYS_vserver:
            return "SYS_vserver";
#endif
#ifdef SYS_wait4
        case SYS_wait4:
            return "SYS_wait4";
#endif
#ifdef SYS_waitid
        case SYS_waitid:
            return "SYS_waitid";
#endif
#ifdef SYS_waitpid
        case SYS_waitpid:
            return "SYS_waitpid";
#endif
#ifdef SYS_write
        case SYS_write:
            return "SYS_write";
#endif
#ifdef SYS_writev
        case SYS_writev:
            return "SYS_writev";
#endif
    }
    return "UNKNOWN";
}
